"""Att User

Revision ID: 6af3f81fd8ca
Revises: e2dfaa27a5d6
Create Date: 2023-09-06 00:49:43.899848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af3f81fd8ca'
down_revision: Union[str, None] = 'e2dfaa27a5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
